export type Currency = 'Usd' | 'Usdt' | 'Ltc'
// TODO check full list and icons for it
// | 'Rouble'
// | 'Bnb'
// | 'Trc'
// | 'Erc20'
// | 'Megafon'
// | 'Nft'
// | 'Usdt'
// | 'Ethereum'
// | 'Ltc'
// | 'Vega'
// | 'Sol'
// | 'YouMoney'
// | 'Btc'
// | 'Qiwi'
// | 'Bep20'
